### PR TITLE
Added Visual Studio 2015 Support

### PR DESCRIPTION
**Pull request by keithjjones**
Added support for the current Visual Studio 2015 development
environment.

### CODE REVIEW

**Comment by mrexodia** [comment]
hello,

I recommend doing this again but then without commiting log files and also without changing the existing projects and solution.

**Comment by keithjjones** [comment]
The whole purpose of updating the project to VS2015 changes the existing projects and solutions.  You have to change them to the 2015 tools to compile with VS2015.  How do you propose keeping the projects and solutions the same and being able to compile them in VS2015?

**Comment by keithjjones** [comment]
I am closing this and sending a new pull request without the logs.  If you want to let me know your ideas about the project and solution files, please do.

**Comment by keithjjones** [comment]
Pull request #375 has been submitted.

**Pull request closed without merging**
