### PR TITLE
Add Visual Studio 2015 Support with NuGet

### PR DESCRIPTION
**Pull request by kallanreed**
Adding build support for VS2015. The binary dependencies are contained in a NuGet package. Visual Studio will download the package automatically when yara is built. The NuGet package is [here](https://www.nuget.org/packages/yara-vs2015-binary-dependencies/) and the package project is [here](https://github.com/kallanreed/yara-vs2015-binary-dependencies).

This solution keeps tool chain specific binaries out of the yara repo, doesn't complicate the repo with submodules and still provides a good "clone and compile" experience for VS2015 contributors. The NuGet package version is locked to the specific version referenced in the checked in project file so so future updates to the NuGet package are "opt in".

This hopefully addresses concerns raised in #410 and includes changes from #408 (pthread impl).

### CODE REVIEW

**Comment by kallanreed** [comment]
cc: @keithjjones

**Comment by keithjjones** [comment]
I thought Nuget was mainly for .NET?  How does it work in this case?
:+1:

**Comment by kallanreed** [comment]
Nuget added support for native targets around VS2012. Basically it's just the include headers and the libs packaged up and a targets file that is injected into the projects so that the projects can reference the package files. I linked to the nuget package project above if you're interested in how it's built.

**Comment by keithjjones** [comment]
That is pretty cool!  Thanks for teaching me something.

**Comment by keithjjones** [comment]
Apparently this PR has conflicts already.  Something must have changed since last night.

**Comment by keithjjones** [comment]
I was hoping this would make it into master at some point.

**Comment by plusvic** [comment]
Don't worry, this is going to be merged in the master branch, it's just that I haven't found the time to do it. That's why I'm only merging simple patches that don't require too much effort.

**Comment by jacob-baines** [comment]
For what its worth, I've tested/used this successfully and am also looking forward to seeing it merged in.

**Comment by plusvic** [comment]
Manually merged.

**Pull request closed without merging**
