### PR TITLE
Fix PRINT_MODULE_DATA.

### PR DESCRIPTION
**Pull request by wxsBSD**
This fixes things so that PRINT_MODULE_DATA works correctly.

### CODE REVIEW

**Comment by wxsBSD** [comment]
No clue why I didn't see it earlier but I was looking to see if this existed before I wrote my own implementation, glad I found it. :smile: This is a great feature!

**Comment by wxsBSD** [comment]
I also changed string printing so that non-printable characters are printed in hex form.

**Comment by wxsBSD** [comment]
Would you be open to changing it from a compile-time knob to a run-time option? Having this ability is a great way to debug signatures. I can keep a binary with it turned on around but I suspect making it a run-time option is going to increase usage and by extension the new module features!

**Comment by plusvic** [comment]
Sure, I think that a run-time option is a better way to control this feature. Do you plan to implement it?

**Comment by wxsBSD** [comment]
Yes. I will try and implement it in the next couple of weeks.

**Pull request merged**
